version: '3.9'

services:
  webtop:
    container_name: webtop
    image: lscr.io/linuxserver/webtop:latest
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuching
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    volumes:
      - /data/webstop/data:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3000:3000
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "2gb" #optional
    restart: unless-stopped